# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "npm" # Specifying npm for a React project
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly" # Monthly updates as requested
    open-pull-requests-limit: 10
    # Allow manual triggers via GitHub Actions
    labels:
      - "dependencies"
      - "npm"
    # Enable manual triggers
    assignees:
      - "$GITHUB_ACTOR" # Will assign the PR to the user who triggered it
    # Enable automated security fixes to be received
    allow:
      - dependency-type: "all"
